- name: download minio
  get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    dest: /usr/local/bin/minio
    mode: '0755'

- name: Ensure group "minio" exists
  ansible.builtin.group:
    name: minio
    state: present

- name: Add user 
  ansible.builtin.user:
    name: minio
    groups: minio
    password: "{{ 'minio' | password_hash('sha512') }}"

- name: copy minio default config 
  template:
    src: minio
    dest: /etc/default/minio
    owner: root
    group: root
    mode: '0644'

- name: copy systemd config 
  template:
    src: minio.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Start MinIO Services
  systemd:
    name: minio  
    state: started
    daemon_reload: yes
    enabled: yes